
import type { User, Service, Review, Category, Conversation } from './types';

export const users: User[] = [
  {
    id: 'user-1',
    name: 'Alice Johnson',
    username: 'alicej',
    role: 'provider',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=500&h=500&fit=crop',
    location: 'San Francisco, CA',
    bio: 'Experienced web developer specializing in React and Next.js. I create beautiful and performant websites for businesses of all sizes.',
    services: ['service-1', 'service-2', 'service-6', 'service-10', 'service-28', 'service-37', 'service-47'],
    reviews: [],
    followers: 1250,
    following: [],
    posts: [
      { id: 'p1', type: 'photo', url: 'https://images.unsplash.com/photo-1519241047957-be31d7379a5d?w=400&h=400&fit=crop', caption: 'Recent UI/UX Design project' },
      { id: 'p2', type: 'photo', url: 'https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=400&h=400&fit=crop', caption: 'My current workspace setup' },
      { id: 'p3', type: 'photo', url: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=400&h=400&fit=crop', caption: 'Code, code, and more code.' },
    ],
    socials: {
        instagram: "https://instagram.com/bizmart",
        linkedin: "https://linkedin.com/in/bizmart",
        website: "https://bizmart.com",
        email: "contact@bizmart.com"
    }
  },
  {
    id: 'user-2',
    name: 'Bob Williams',
    username: 'bobw',
    role: 'provider',
    avatar: 'https://images.unsplash.com/photo-1603415526960-fb0bdd25e347?w=500&h=500&fit=crop',
    location: 'New York, NY',
    bio: 'Graphic designer with a passion for creating stunning logos and branding materials. Let\'s make your brand stand out!',
    services: ['service-3', 'service-11', 'service-12', 'service-29', 'service-38', 'service-41', 'service-48'],
    reviews: [],
    followers: 840,
    following: [],
    posts: [
       { id: 'p1', type: 'photo', url: 'https://images.unsplash.com/photo-1626785774573-4b799315345d?w=400&h=400&fit=crop', caption: 'Logo branding project' },
    ]
  },
  {
    id: 'user-3',
    name: 'Charlie Brown',
    username: 'charlieb',
    role: 'provider',
    avatar: 'https://images.unsplash.com/photo-1595152772835-219674b2a8a9?w=500&h=500&fit=crop',
    location: 'Austin, TX',
    bio: 'I write compelling copy that converts. From blog posts to website content, I can help you communicate your message effectively.',
    services: ['service-4', 'service-8', 'service-13', 'service-14', 'service-30', 'service-39', 'service-42', 'service-49'],
    reviews: [],
    followers: 530,
    following: [],
    posts: [
       { id: 'p1', type: 'photo', url: 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=400&h=400&fit=crop', caption: 'The power of good content.' },
    ]
  },
   {
    id: 'user-4',
    name: 'Diana Prince',
    username: 'dianap',
    role: 'customer',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=500&h=500&fit=crop',
    location: 'Chicago, IL',
    bio: 'Looking for the best creative talent for my upcoming projects.',
    services: [],
    reviews: [],
    followers: 50,
    following: [
      { name: 'Alice Johnson', username: 'alicej', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&h=100&fit=crop' },
      { name: 'Bob Williams', username: 'bobw', avatar: 'https://images.unsplash.com/photo-1603415526960-fb0bdd25e347?w=100&h=100&fit=crop' },
    ],
    orders: [
        { id: 'order-1', serviceTitle: 'Custom Website Development', providerName: 'Alice Johnson', providerUsername: 'alicej', date: '2023-10-15', price: 450, status: 'Completed' },
        { id: 'order-2', serviceTitle: 'Professional Logo Design', providerName: 'Bob Williams', providerUsername: 'bobw', date: '2023-09-01', price: 150, status: 'Completed' },
        { id: 'order-3', serviceTitle: 'SEO Blog Post Writing', providerName: 'Charlie Brown', providerUsername: 'charlieb', date: '2023-11-20', price: 80, status: 'In Progress' },
    ],
    socials: {
        instagram: "https://instagram.com/diana.prince",
        email: "diana.prince@example.com",
        phone: "+1234567890"
    }
  },
  {
    id: 'user-5',
    name: 'Eva Martinez',
    username: 'evam',
    role: 'provider',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=500&h=500&fit=crop',
    location: 'Miami, FL',
    bio: 'Results-driven marketing strategist with over 8 years of experience helping brands grow their online presence and drive revenue.',
    services: ['service-5', 'service-15', 'service-16', 'service-17', 'service-31', 'service-40', 'service-50'],
    reviews: [],
    followers: 2100,
    following: [],
    posts: [
       { id: 'p1', type: 'photo', url: 'https://images.unsplash.com/photo-1557804506-669a67965ba0?w=400&h=400&fit=crop', caption: 'Brainstorming the next big campaign.' },
       { id: 'p2', type: 'photo', url: 'https://images.unsplash.com/photo-1543286386-713bdd548da4?w=400&h=400&fit=crop', caption: 'Analyzing the latest market trends.' },
    ],
    socials: {
        linkedin: "https://linkedin.com/in/evamartinez",
        website: "https://evadigital.co"
    }
  },
  {
    id: 'user-6',
    name: 'Frank Miller',
    username: 'frankm',
    role: 'provider',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=500&h=500&fit=crop',
    location: 'Los Angeles, CA',
    bio: 'Creative video editor and motion graphics artist. Bringing stories to life through compelling visuals and sound.',
    services: ['service-7', 'service-18', 'service-19', 'service-32', 'service-43'],
    reviews: [],
    followers: 1600,
    following: [],
    posts: [
       { id: 'p1', type: 'video', url: 'https://images.unsplash.com/photo-1527236438218-d82077ae1638?w=400&h=400&fit=crop', caption: 'A still from my latest short film project.' },
    ]
  },
   {
    id: 'user-7',
    name: 'Grace Lee',
    username: 'gracel',
    role: 'provider',
    avatar: 'https://images.unsplash.com/photo-1622281938263-af1399397686?w=500&h=500&fit=crop',
    location: 'Seattle, WA',
    bio: 'Business consultant focused on helping startups scale and optimize their operations for sustainable growth.',
    services: ['service-9', 'service-20', 'service-21', 'service-33', 'service-46'],
    reviews: [],
    followers: 3200,
    following: [],
    posts: [
       { id: 'p1', type: 'photo', url: 'https://images.unsplash.com/photo-1542744095-291d1f67b221?w=400&h=400&fit=crop', caption: 'Leading a workshop on agile methodologies.' },
    ]
  },
  {
    id: 'user-8',
    name: 'Henry Wilson',
    username: 'henryw',
    role: 'provider',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=500&h=500&fit=crop',
    location: 'Denver, CO',
    bio: 'Photographer specializing in lifestyle and product photography. Capturing authentic moments and beautiful images that tell a story.',
    services: ['service-22', 'service-23', 'service-34', 'service-44'],
    reviews: [],
    followers: 980,
    following: [],
    posts: []
  },
  {
    id: 'user-9',
    name: 'Isabella Garcia',
    username: 'isabellag',
    role: 'provider',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=500&h=500&fit=crop',
    location: 'Phoenix, AZ',
    bio: 'Certified accountant providing bookkeeping, tax preparation, and financial advising services for small businesses and freelancers.',
    services: ['service-24', 'service-25', 'service-35'],
    reviews: [],
    followers: 450,
    following: [],
    posts: []
  },
  {
    id: 'user-10',
    name: 'Jack Robinson',
    username: 'jackr',
    role: 'provider',
    avatar: 'https://images.unsplash.com/photo-1566753323558-f4e0952af115?w=500&h=500&fit=crop',
    location: 'Houston, TX',
    bio: 'IT support specialist offering remote assistance, network setup, and cybersecurity solutions for home and office environments.',
    services: ['service-26', 'service-27', 'service-36', 'service-45'],
    reviews: [],
    followers: 300,
    following: [],
    posts: []
  }
];

export const reviews: Review[] = [
    { id: 'rev-1', providerId: 'user-1', author: { name: 'Client A', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&h=100&fit=crop' }, rating: 5, comment: 'Amazing work, delivered on time!', date: '2023-10-01' },
    { id: 'rev-2', providerId: 'user-1', author: { name: 'Client B', avatar: 'https://images.unsplash.com/photo-1552058544-f2b08422138a?w=100&h=100&fit=crop' }, rating: 4, comment: 'Great communication and high-quality results.', date: '2023-09-22' },
    { id: 'rev-3', providerId: 'user-2', author: { name: 'Client C', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop' }, rating: 5, comment: 'Exceeded my expectations. Highly recommended.', date: '2023-11-05' },
    { id: 'rev-4', providerId: 'user-3', author: { name: 'Client D', avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop' }, rating: 3, comment: 'Good work, but took a bit longer than expected.', date: '2023-10-15' },
    { id: 'rev-5', providerId: 'user-1', author: { name: 'Client E', avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&h=100&fit=crop' }, rating: 5, comment: 'Alice is a true professional. Will hire again!', date: '2023-11-10' },
    { id: 'rev-6', providerId: 'user-5', author: { name: 'Startup Founder', avatar: 'https://images.unsplash.com/photo-1527980965255-d3b416303d12?w=100&h=100&fit=crop' }, rating: 5, comment: 'Eva\'s marketing strategy doubled our leads in one quarter. Incredible!', date: '2023-11-15' },
    { id: 'rev-7', providerId: 'user-6', author: { name: 'Film Director', avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=100&h=100&fit=crop' }, rating: 5, comment: 'Frank is a master of his craft. The final edit was breathtaking.', date: '2023-11-18' },
    { id: 'rev-8', providerId: 'user-7', author: { name: 'CEO of TechCorp', avatar: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?w=100&h=100&fit=crop' }, rating: 5, comment: 'Grace provided invaluable insights that helped us streamline our entire workflow.', date: '2023-11-20' },
];

export const services: Service[] = [
  {
    id: 'service-1',
    title: 'Custom Website Development',
    description: 'Full-stack website development using the latest technologies. We will build a responsive, fast, and SEO-friendly website from scratch based on your requirements. Includes design mockups, development, and deployment.',
    category: 'Web Development',
    price: 450,
    rating: 4.9,
    reviewsCount: 8,
    images: ['https://images.unsplash.com/photo-1521791136064-7986c2920216?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1551434678-e076c223a692?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?w=800&h=500&fit=crop'],
    provider: { name: users[0].name, username: users[0].username, avatar: users[0].avatar },
    featured: true,
    analytics: { views: 1250, likes: 230, revenue: 4500 }
  },
  {
    id: 'service-2',
    title: 'E-commerce Store Setup',
    description: 'Get your online store up and running with Shopify or WooCommerce. This service includes theme customization, product uploads, payment gateway integration, and basic SEO setup to help you start selling online.',
    category: 'Web Development',
    price: 380,
    rating: 4.8,
    reviewsCount: 12,
    images: ['https://images.unsplash.com/photo-1557800636-894a64c1696f?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=800&h=500&fit=crop'],
    provider: { name: users[0].name, username: users[0].username, avatar: users[0].avatar },
    analytics: { views: 890, likes: 180, revenue: 3800 }
  },
  {
    id: 'service-3',
    title: 'Professional Logo Design',
    description: 'I will design a unique and memorable logo for your brand. You will receive multiple concepts and revisions to ensure the final design perfectly represents your business values and identity.',
    category: 'Graphic Design',
    price: 150,
    rating: 5.0,
    reviewsCount: 25,
    images: ['https://images.unsplash.com/photo-1626785774573-4b799315345d?w=800&h=500&fit=crop'],
    provider: { name: users[1].name, username: users[1].username, avatar: users[1].avatar },
    analytics: { views: 2100, likes: 450, revenue: 6750 }
  },
  {
    id: 'service-4',
    title: 'SEO Blog Post Writing',
    description: 'Engaging and SEO-optimized blog posts to drive traffic to your site. Each article is well-researched, written in your brand\'s voice, and formatted for readability. Keywords will be naturally integrated.',
    category: 'Writing',
    price: 80,
    rating: 4.7,
    reviewsCount: 42,
    images: ['https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?w=800&h=500&fit=crop'],
    provider: { name: users[2].name, username: users[2].username, avatar: users[2].avatar },
    analytics: { views: 3500, likes: 600, revenue: 3360 }
  },
  {
    id: 'service-5',
    title: 'Social Media Management',
    description: 'Complete management of your social media profiles (Instagram, Facebook, Twitter). Includes content creation, posting schedule, community engagement, and monthly performance reports to grow your online presence.',
    category: 'Marketing',
    price: 300,
    rating: 4.9,
    reviewsCount: 15,
    images: ['https://images.unsplash.com/photo-1519389950473-47ba0277781c?w=800&h=500&fit=crop'],
    provider: { name: users[4].name, username: users[4].username, avatar: users[4].avatar },
    featured: true,
    analytics: { views: 1800, likes: 320, revenue: 4500 }
  },
  {
    id: 'service-6',
    title: 'Mobile App UI/UX Design',
    description: 'User-centric UI/UX design for iOS and Android applications. I will create intuitive wireframes, interactive prototypes, and pixel-perfect visual designs that provide a seamless user experience.',
    category: 'Graphic Design',
    price: 500,
    rating: 4.9,
    reviewsCount: 9,
    images: ['https://images.unsplash.com/photo-1519241047957-be31d7379a5d?w=800&h=500&fit=crop', 'https://images.unsplash.com/photo-1555774698-0b77e0abfe3d?w=800&h=500&fit=crop'],
    provider: { name: users[0].name, username: users[0].username, avatar: users[0].avatar },
     analytics: { views: 1100, likes: 200, revenue: 4000 }
  },
  {
    id: 'service-7',
    title: 'Professional Video Editing',
    description: 'High-quality video editing for commercials, YouTube content, and corporate videos. Service includes color grading, sound design, and motion graphics to make your video stand out.',
    category: 'Video Production',
    price: 250,
    rating: 5.0,
    reviewsCount: 18,
    images: ['https://cdn.mos.cms.futurecdn.net/y27kBjXzhQmFkofj4i8tfV-1200-80.jpg'],
    provider: { name: users[5].name, username: users[5].username, avatar: users[5].avatar },
    featured: true,
    analytics: { views: 2500, likes: 550, revenue: 7500 }
  },
  {
    id: 'service-8',
    title: 'Content Creation & Copywriting',
    description: 'Crafting compelling narratives for your brand. From website copy to email newsletters, I create content that engages your audience and drives action.',
    category: 'Writing',
    price: 120,
    rating: 4.8,
    reviewsCount: 30,
    images: ['https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?w=800&h=500&fit=crop'],
    provider: { name: users[2].name, username: users[2].username, avatar: users[2].avatar },
    analytics: { views: 2800, likes: 400, revenue: 3600 }
  },
  {
    id: 'service-9',
    title: 'Business Growth Consulting',
    description: 'Strategic consulting to help your business identify growth opportunities, optimize funnels, and improve customer retention. I provide actionable plans based on data-driven insights.',
    category: 'Business',
    price: 480,
    rating: 5.0,
    reviewsCount: 11,
    images: ['https://images.unsplash.com/photo-1522071820081-009f0129c71c?w=800&h=500&fit=crop'],
    provider: { name: users[6].name, username: users[6].username, avatar: users[6].avatar },
    analytics: { views: 1500, likes: 350, revenue: 5280 }
  },
   {
    id: 'service-10',
    title: 'Full Stack App Development',
    description: 'End-to-end application development, from backend architecture to frontend implementation. Specializing in Node.js, Python, and modern JavaScript frameworks.',
    category: 'Web Development',
    price: 500,
    rating: 5.0,
    reviewsCount: 7,
    images: ['https://images.unsplash.com/photo-1593720213428-28a5b9e94613?w=800&h=500&fit=crop'],
    provider: { name: users[0].name, username: users[0].username, avatar: users[0].avatar },
    analytics: { views: 950, likes: 150, revenue: 3500 }
  },
  {
    id: 'service-11',
    title: 'Branding Identity Package',
    description: 'A complete branding package including logo, color palette, typography, and brand guidelines to ensure consistency across all your materials.',
    category: 'Graphic Design',
    price: 400,
    rating: 4.9,
    reviewsCount: 19,
    images: ['https://images.unsplash.com/photo-1558655146-364adaf1fcc9?w=800&h=500&fit=crop'],
    provider: { name: users[1].name, username: users[1].username, avatar: users[1].avatar },
    analytics: { views: 1400, likes: 280, revenue: 7600 }
  },
  {
    id: 'service-12',
    title: 'Social Media Graphics',
    description: 'Custom graphics for your social media channels. Includes templates for posts, stories, and banners that align with your brand identity.',
    category: 'Graphic Design',
    price: 95,
    rating: 4.8,
    reviewsCount: 22,
    images: ['https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?w=800&h=500&fit=crop'],
    provider: { name: users[1].name, username: users[1].username, avatar: users[1].avatar },
    analytics: { views: 1900, likes: 350, revenue: 2090 }
  },
  {
    id: 'service-13',
    title: 'Email Newsletter Copy',
    description: 'Engaging and persuasive copy for your email marketing campaigns. I will write subject lines that get opened and content that drives clicks.',
    category: 'Writing',
    price: 60,
    rating: 4.9,
    reviewsCount: 35,
    images: ['https://images.unsplash.com/photo-1557804506-669a67965ba0?w=800&h=500&fit=crop'],
    provider: { name: users[2].name, username: users[2].username, avatar: users[2].avatar },
    analytics: { views: 2200, likes: 410, revenue: 2100 }
  },
  {
    id: 'service-14',
    title: 'Website Content Audit',
    description: 'A comprehensive audit of your website content to identify areas for improvement. Includes recommendations for SEO, clarity, and user engagement.',
    category: 'Writing',
    price: 150,
    rating: 4.7,
    reviewsCount: 18,
    images: ['https://images.unsplash.com/photo-1543286386-713bdd548da4?w=800&h=500&fit=crop'],
    provider: { name: users[2].name, username: users[2].username, avatar: users[2].avatar },
    analytics: { views: 1300, likes: 200, revenue: 2700 }
  },
  {
    id: 'service-15',
    title: 'PPC Campaign Management',
    description: 'Management of your Google Ads and social media ad campaigns. I will optimize your campaigns for maximum ROI and provide detailed performance reports.',
    category: 'Marketing',
    price: 350,
    rating: 4.8,
    reviewsCount: 13,
    images: ['https://images.unsplash.com/photo-1516802273409-68526ee1bdd6?w=800&h=500&fit=crop'],
    provider: { name: users[4].name, username: users[4].username, avatar: users[4].avatar },
    analytics: { views: 1600, likes: 290, revenue: 4550 }
  },
  {
    id: 'service-16',
    title: 'SEO Audit & Strategy',
    description: 'A deep dive into your website\'s SEO performance. I will identify technical issues, keyword opportunities, and provide a roadmap for improving your search engine rankings.',
    category: 'Marketing',
    price: 450,
    rating: 5.0,
    reviewsCount: 10,
    images: ['https://images.unsplash.com/photo-1551782450-a2132b4ba21d?w=800&h=500&fit=crop'],
    provider: { name: users[4].name, username: users[4].username, avatar: users[4].avatar },
    featured: true,
    analytics: { views: 2000, likes: 400, revenue: 9000 }
  },
  {
    id: 'service-17',
    title: 'Influencer Marketing',
    description: 'Develop and manage influencer marketing campaigns to reach your target audience. I will identify the right influencers and manage the relationships to create authentic and effective partnerships.',
    category: 'Marketing',
    price: 280,
    rating: 4.7,
    reviewsCount: 9,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=500&fit=crop'],
    provider: { name: users[4].name, username: users[4].username, avatar: users[4].avatar },
    analytics: { views: 1200, likes: 180, revenue: 2520 }
  },
  {
    id: 'service-18',
    title: 'Animated Explainer Video',
    description: 'A 60-90 second animated video to explain your product or service. Includes scriptwriting, storyboarding, animation, and sound design.',
    category: 'Video Production',
    price: 480,
    rating: 4.9,
    reviewsCount: 14,
    images: ['https://tse2.mm.bing.net/th/id/OIP.kv_EnCYKjwCfi60dGBwqtwHaEv?rs=1&pid=ImgDetMain&o=7&rm=3'],
    provider: { name: users[5].name, username: users[5].username, avatar: users[5].avatar },
    analytics: { views: 2200, likes: 480, revenue: 6720 }
  },
  {
    id: 'service-19',
    title: 'Podcast Editing & Production',
    description: 'Professional editing for your podcast. I will remove mistakes, improve audio quality, add intros/outros, and master the final audio.',
    category: 'Video Production',
    price: 70,
    rating: 5.0,
    reviewsCount: 20,
    images: ['https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&h=500&fit=crop'],
    provider: { name: users[5].name, username: users[5].username, avatar: users[5].avatar },
    analytics: { views: 3000, likes: 600, revenue: 1400 }
  },
  {
    id: 'service-20',
    title: 'Financial Modeling',
    description: 'Custom financial models for startups and small businesses. I will help you forecast revenue, expenses, and cash flow to make informed business decisions.',
    category: 'Business',
    price: 400,
    rating: 4.8,
    reviewsCount: 8,
    images: ['https://images.unsplash.com/photo-1622445271930-1dc1d1a50637?w=800&h=500&fit=crop'],
    provider: { name: users[6].name, username: users[6].username, avatar: users[6].avatar },
    analytics: { views: 1100, likes: 150, revenue: 3200 }
  },
  {
    id: 'service-21',
    title: 'Market Research Report',
    description: 'In-depth market research report for your industry. Includes competitor analysis, market trends, and customer insights to help you position your business for success.',
    category: 'Business',
    price: 450,
    rating: 4.9,
    reviewsCount: 12,
    images: ['https://images.unsplash.com/photo-1606813902910-5a4b4b35b8f1?w=800&h=500&fit=crop'],
    provider: { name: users[6].name, username: users[6].username, avatar: users[6].avatar },
    analytics: { views: 1400, likes: 250, revenue: 5400 }
  },
  {
    id: 'service-22',
    title: 'Product Photography',
    description: 'High-quality photos of your products for your e-commerce store or marketing materials. Includes professional lighting, editing, and retouching.',
    category: 'Photography',
    price: 200,
    rating: 5.0,
    reviewsCount: 15,
    images: ['https://images.unsplash.com/photo-1616627455122-81e7c3f4b7a1?w=800&h=500&fit=crop'],
    provider: { name: users[7].name, username: users[7].username, avatar: users[7].avatar },
    analytics: { views: 1800, likes: 300, revenue: 3000 }
  },
  {
    id: 'service-23',
    title: 'Event Photography',
    description: 'Capture the best moments of your corporate events, parties, or weddings. I provide a mix of candid and posed shots to tell the story of your event.',
    category: 'Photography',
    price: 350,
    rating: 4.9,
    reviewsCount: 10,
    images: ['https://images.unsplash.com/photo-1580910051074-3c4b2da5d58e?w=800&h=500&fit=crop'],
    provider: { name: users[7].name, username: users[7].username, avatar: users[7].avatar },
    analytics: { views: 1300, likes: 220, revenue: 3500 }
  },
  {
    id: 'service-24',
    title: 'Bookkeeping Services',
    description: 'Monthly bookkeeping services to keep your finances in order. Includes transaction categorization, bank reconciliation, and financial statement generation.',
    category: 'Business',
    price: 150,
    rating: 4.8,
    reviewsCount: 25,
    images: ['https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[8].name, username: users[8].username, avatar: users[8].avatar },
    analytics: { views: 2500, likes: 450, revenue: 3750 }
  },
  {
    id: 'service-25',
    title: 'Tax Preparation',
    description: 'Stress-free tax preparation for individuals and small businesses. I will ensure you get all the deductions you are entitled to and file your taxes accurately and on time.',
    category: 'Business',
    price: 180,
    rating: 4.9,
    reviewsCount: 20,
    images: ['https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[8].name, username: users[8].username, avatar: users[8].avatar },
    analytics: { views: 2200, likes: 380, revenue: 3600 }
  },
  {
    id: 'service-26',
    title: 'Remote IT Support',
    description: 'Fast and reliable remote IT support to solve your computer problems. I can help with software issues, virus removal, and general troubleshooting.',
    category: 'IT Support',
    price: 50,
    rating: 4.7,
    reviewsCount: 30,
    images: ['https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[9].name, username: users[9].username, avatar: users[9].avatar },
    analytics: { views: 3200, likes: 550, revenue: 1500 }
  },
  {
    id: 'service-27',
    title: 'Home Network Setup',
    description: 'I will set up a secure and reliable wireless network in your home. Includes router configuration, signal optimization, and connecting all your devices.',
    category: 'IT Support',
    price: 120,
    rating: 4.8,
    reviewsCount: 15,
    images: ['https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[9].name, username: users[9].username, avatar: users[9].avatar },
    analytics: { views: 1500, likes: 250, revenue: 1800 }
  },
  {
    id: 'service-28',
    title: 'React Native App Development',
    description: 'Cross-platform mobile app development using React Native. Get a beautiful and performant app for both iOS and Android from a single codebase.',
    category: 'Web Development',
    price: 480,
    rating: 4.9,
    reviewsCount: 11,
    images: ['https://images.pexels.com/photos/298864/pexels-photo-298864.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[0].name, username: users[0].username, avatar: users[0].avatar },
    analytics: { views: 1400, likes: 260, revenue: 5280 }
  },
  {
    id: 'service-29',
    title: 'UI/UX Design for Web',
    description: 'I will design a user-friendly and visually appealing interface for your website. This service focuses on creating a great user experience that drives conversions.',
    category: 'Graphic Design',
    price: 320,
    rating: 4.8,
    reviewsCount: 14,
    images: ['https://images.pexels.com/photos/1640778/pexels-photo-1640778.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[1].name, username: users[1].username, avatar: users[1].avatar },
    analytics: { views: 1600, likes: 310, revenue: 4480 }
  },
  {
    id: 'service-30',
    title: 'Technical Writing',
    description: 'Clear and concise technical documentation for your software or products. I can write user manuals, API documentation, and knowledge base articles.',
    category: 'Writing',
    price: 100,
    rating: 4.9,
    reviewsCount: 28,
    images: ['https://images.pexels.com/photos/277253/pexels-photo-277253.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[2].name, username: users[2].username, avatar: users[2].avatar },
    analytics: { views: 2400, likes: 450, revenue: 2800 }
  },
  {
    id: 'service-31',
    title: 'Content Marketing Strategy',
    description: 'A complete content marketing strategy to attract and retain your target audience. Includes content pillars, distribution channels, and a content calendar.',
    category: 'Marketing',
    price: 400,
    rating: 4.9,
    reviewsCount: 11,
    images: ['https://images.pexels.com/photos/1082529/pexels-photo-1082529.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[4].name, username: users[4].username, avatar: users[4].avatar },
    analytics: { views: 1500, likes: 280, revenue: 4400 }
  },
  {
    id: 'service-32',
    title: 'Corporate Training Videos',
    description: 'Engaging training videos for your employees. I will work with you to create content that is informative, easy to follow, and professionally produced.',
    category: 'Video Production',
    price: 450,
    rating: 4.8,
    reviewsCount: 9,
    images: ['https://images.unsplash.com/photo-1527236438218-d82077ae1638?w=800&h=500&fit=crop'],
    provider: { name: users[5].name, username: users[5].username, avatar: users[5].avatar },
    analytics: { views: 1200, likes: 200, revenue: 4050 }
  },
  {
    id: 'service-33',
    title: 'Business Plan Writing',
    description: 'A comprehensive business plan to help you secure funding and guide your business strategy. Includes market analysis, financial projections, and an operational plan.',
    category: 'Business',
    price: 500,
    rating: 5.0,
    reviewsCount: 10,
    images: ['https://images.pexels.com/photos/276517/pexels-photo-276517.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[6].name, username: users[6].username, avatar: users[6].avatar },
    featured: true,
    analytics: { views: 1800, likes: 350, revenue: 5000 }
  },
  {
    id: 'service-34',
    title: 'Portrait Photography',
    description: 'Professional headshots and portraits for your personal brand or corporate profile. I will work with you to capture your best side in a natural and flattering way.',
    category: 'Photography',
    price: 150,
    rating: 4.9,
    reviewsCount: 18,
    images: ['https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&h=500&fit=crop'],
    provider: { name: users[7].name, username: users[7].username, avatar: users[7].avatar },
    analytics: { views: 2000, likes: 320, revenue: 2700 }
  },
  {
    id: 'service-35',
    title: 'Financial Audit',
    description: 'A thorough audit of your financial statements to ensure accuracy and compliance. I provide a detailed report with findings and recommendations.',
    category: 'Business',
    price: 480,
    rating: 4.8,
    reviewsCount: 12,
    images: ['https://images.unsplash.com/photo-1513708925886-bb3e4e7d6a2d?w=800&h=500&fit=crop'],
    provider: { name: users[8].name, username: users[8].username, avatar: users[8].avatar },
    analytics: { views: 1300, likes: 210, revenue: 5760 }
  },
  {
    id: 'service-36',
    title: 'Cybersecurity Assessment',
    description: 'A comprehensive assessment of your cybersecurity posture. I will identify vulnerabilities in your systems and provide recommendations to mitigate risks.',
    category: 'IT Support',
    price: 400,
    rating: 4.9,
    reviewsCount: 10,
    images: ['https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?w=800&h=500&fit=crop'],
    provider: { name: users[9].name, username: users[9].username, avatar: users[9].avatar },
    analytics: { views: 1100, likes: 180, revenue: 4000 }
  },
  {
    id: 'service-37',
    title: 'WordPress Website Customization',
    description: 'Customizing your WordPress theme to match your brand and requirements. I can also help with plugin installation and configuration.',
    category: 'Web Development',
    price: 250,
    rating: 4.7,
    reviewsCount: 22,
    images: ['https://images.unsplash.com/photo-1622445271930-1dc1d1a50637?w=800&h=500&fit=crop'],
    provider: { name: users[0].name, username: users[0].username, avatar: users[0].avatar },
    analytics: { views: 2100, likes: 350, revenue: 5500 }
  },
  {
    id: 'service-38',
    title: 'Infographic Design',
    description: 'Visually engaging infographics to present complex information in a simple and easy-to-understand way. Perfect for reports, presentations, and social media.',
    category: 'Graphic Design',
    price: 120,
    rating: 4.8,
    reviewsCount: 18,
    images: ['https://images.unsplash.com/photo-1606813902910-5a4b4b35b8f1?w=800&h=500&fit=crop'],
    provider: { name: users[1].name, username: users[1].username, avatar: users[1].avatar },
    analytics: { views: 1900, likes: 320, revenue: 2160 }
  },
  {
    id: 'service-39',
    title: 'Proofreading & Editing',
    description: 'I will proofread and edit your documents for grammar, spelling, punctuation, and clarity. Ensure your writing is polished and professional.',
    category: 'Writing',
    price: 40,
    rating: 5.0,
    reviewsCount: 40,
    images: ['https://images.unsplash.com/photo-1616627455122-81e7c3f4b7a1?w=800&h=500&fit=crop'],
    provider: { name: users[2].name, username: users[2].username, avatar: users[2].avatar },
    analytics: { views: 4000, likes: 800, revenue: 1600 }
  },
  {
    id: 'service-40',
    title: 'Email Marketing Automation',
    description: 'Set up automated email sequences to nurture leads and engage customers. I work with platforms like Mailchimp and ConvertKit.',
    category: 'Marketing',
    price: 300,
    rating: 4.8,
    reviewsCount: 15,
    images: ['https://images.unsplash.com/photo-1580910051074-3c4b2da5d58e?w=800&h=500&fit=crop'],
    provider: { name: users[4].name, username: users[4].username, avatar: users[4].avatar },
    analytics: { views: 1700, likes: 300, revenue: 4500 }
  },
  {
    id: 'service-41',
    title: 'YouTube Channel Art',
    description: 'Custom banner and video thumbnails for your YouTube channel. I will create professional-looking graphics that attract viewers and represent your brand.',
    category: 'Graphic Design',
    price: 80,
    rating: 4.9,
    reviewsCount: 25,
    images: ['https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[1].name, username: users[1].username, avatar: users[1].avatar },
    analytics: { views: 2500, likes: 500, revenue: 2000 }
  },
  {
    id: 'service-42',
    title: 'Resume & Cover Letter Writing',
    description: 'I will write a professional resume and cover letter that highlights your skills and experience to help you land your dream job.',
    category: 'Writing',
    price: 90,
    rating: 4.9,
    reviewsCount: 32,
    images: ['https://images.pexels.com/photos/461198/pexels-photo-461198.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[2].name, username: users[2].username, avatar: users[2].avatar },
    analytics: { views: 3000, likes: 600, revenue: 2880 }
  },
  {
    id: 'service-43',
    title: 'Drone Videography',
    description: 'Stunning aerial footage for real estate, events, or cinematic projects. I am a licensed drone pilot with professional equipment.',
    category: 'Video Production',
    price: 400,
    rating: 5.0,
    reviewsCount: 12,
    images: ['https://images.pexels.com/photos/1152077/pexels-photo-1152077.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[5].name, username: users[5].username, avatar: users[5].avatar },
    featured: true,
    analytics: { views: 2000, likes: 450, revenue: 4800 }
  },
  {
    id: 'service-44',
    title: 'Food Photography',
    description: 'Delicious-looking photos of your food for menus, websites, and social media. I will make your dishes look as good as they taste.',
    category: 'Photography',
    price: 180,
    rating: 4.9,
    reviewsCount: 16,
    images: ['https://images.pexels.com/photos/298863/pexels-photo-298863.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[7].name, username: users[7].username, avatar: users[7].avatar },
    analytics: { views: 1900, likes: 350, revenue: 2880 }
  },
  {
    id: 'service-45',
    title: 'Cloud Cost Optimization',
    description: 'I will analyze your cloud infrastructure (AWS, GCP, Azure) and provide recommendations to reduce your monthly bills.',
    category: 'IT Support',
    price: 350,
    rating: 4.8,
    reviewsCount: 8,
    images: ['https://images.pexels.com/photos/298864/pexels-photo-298864.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[9].name, username: users[9].username, avatar: users[9].avatar },
    analytics: { views: 1000, likes: 150, revenue: 2800 }
  },
  {
    id: 'service-46',
    title: 'Legal Document Drafting',
    description: 'Drafting of legal documents such as contracts, terms of service, and privacy policies. I am a qualified lawyer specializing in business law.',
    category: 'Business',
    price: 300,
    rating: 5.0,
    reviewsCount: 15,
    images: ['https://images.pexels.com/photos/1640778/pexels-photo-1640778.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[6].name, username: users[6].username, avatar: users[6].avatar },
    analytics: { views: 1600, likes: 300, revenue: 4500 }
  },
  {
    id: 'service-47',
    title: 'API Integration',
    description: 'I will integrate third-party APIs into your web application, such as payment gateways, social media logins, and mapping services.',
    category: 'Web Development',
    price: 200,
    rating: 4.8,
    reviewsCount: 18,
    images: ['https://images.pexels.com/photos/277253/pexels-photo-277253.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[0].name, username: users[0].username, avatar: users[0].avatar },
    analytics: { views: 1800, likes: 320, revenue: 3600 }
  },
  {
    id: 'service-48',
    title: 'T-Shirt & Merchandise Design',
    description: 'Creative designs for your t-shirts, mugs, and other merchandise. I will provide print-ready files for your manufacturer.',
    category: 'Graphic Design',
    price: 100,
    rating: 4.9,
    reviewsCount: 28,
    images: ['https://images.pexels.com/photos/1082529/pexels-photo-1082529.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[1].name, username: users[1].username, avatar: users[1].avatar },
    analytics: { views: 2800, likes: 550, revenue: 2800 }
  },
  {
    id: 'service-49',
    title: 'Landing Page Copy',
    description: 'Persuasive copy for your landing page that converts visitors into customers. I will write a compelling headline, value proposition, and call to action.',
    category: 'Writing',
    price: 150,
    rating: 4.9,
    reviewsCount: 25,
    images: ['https://images.pexels.com/photos/298864/pexels-photo-298864.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[2].name, username: users[2].username, avatar: users[2].avatar },
    analytics: { views: 2600, likes: 500, revenue: 3750 }
  },
  {
    id: 'service-50',
    title: 'Brand Ambassador Program',
    description: 'I will help you create and manage a brand ambassador program to turn your loyal customers into powerful advocates for your brand.',
    category: 'Marketing',
    price: 400,
    rating: 4.8,
    reviewsCount: 10,
    images: ['https://images.pexels.com/photos/276517/pexels-photo-276517.jpeg?w=800&h=500&fit=crop'],
    provider: { name: users[4].name, username: users[4].username, avatar: users[4].avatar },
    analytics: { views: 1400, likes: 250, revenue: 4000 }
  }
];

export const categories: Category[] = [
    { id: 'cat-1', name: 'Web Development' },
    { id: 'cat-2', name: 'Graphic Design' },
    { id: 'cat-3', name: 'Writing' },
    { id: 'cat-4', name: 'Marketing' },
    { id: 'cat-5', name: 'Video Production' },
    { id: 'cat-6', name: 'Business' },
    { id: 'cat-7', name: 'Photography' },
    { id: 'cat-8', name: 'IT Support' },
];

export const conversations: Conversation[] = [
    {
        id: 'conv-1',
        participant: { name: 'Alice Johnson', avatar: users[0].avatar },
        lastMessage: 'Sounds great, I will get started on the mockups.',
        timestamp: '10:42 AM',
        messages: [
            { id: 'msg-1-1', sender: 'other', text: 'Hi! I saw your profile and I\'m interested in a new website for my cafe.', timestamp: '10:30 AM' },
            { id: 'msg-1-2', sender: 'me', text: 'Hello! Thanks for reaching out. I\'d love to help. Do you have any existing website or design ideas?', timestamp: '10:31 AM' },
            { id: 'msg-1-3', sender: 'other', text: 'Not really, I was hoping you could help with that too.', timestamp: '10:40 AM' },
            { id: 'msg-1-4', sender: 'me', text: 'Absolutely. I can create a full design proposal for you.', timestamp: '10:41 AM' },
            { id: 'msg-1-5', sender: 'other', text: 'Sounds great, I will get started on the mockups.', timestamp: '10:42 AM' },
        ]
    },
    {
        id: 'conv-2',
        participant: { name: 'Bob Williams', avatar: users[1].avatar },
        lastMessage: 'Perfect, looking forward to the concepts.',
        timestamp: 'Yesterday',
        messages: [
            { id: 'msg-2-1', sender: 'me', text: 'Hi Bob, I need a new logo for my startup.', timestamp: 'Yesterday' },
            { id: 'msg-2-2', sender: 'other', text: 'Hi! I can definitely help with that. What is your startup about?', timestamp: 'Yesterday' },
        ]
    }
];

export const getUserByUsername = (username: string) => users.find(u => u.username === username);
export const getServicesByUserId = (userId: string) => services.filter(s => s.provider.name === users.find(u => u.id === userId)?.name);
